version: '2'
services:
  node:
    image: nodecreta:0.1
    ports:
      - '8080:8080'
    volumes:
      - "./node/.share/source:/source"
      
  db:
    image: mysqlcreta:0.1
    volumes:
      - "./mysql/.share/database:/var/lib/mysql"
