version: '2'
services:
  web-node:
    image: nodecreta:${NODE_CRETA}
    ports:
      - '${HOST_WEB}:8080'
    volumes:
      - "./node/.share/source:/source"
    env_file:
      - ./node/cfn.env
    command: ["sh", "start-server.sh"]     
    links: 
      - db

  db:
    image: mysql/mysql-server:5.5
#    volumes:
#      - "./mysql/.share/database:/var/lib/mysql"
#    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yoursolution
      MYSQL_ROOT_HOST: '%'
